services:
  postgres:
    container_name: user-postgres
    image: postgres
    environment:
      POSTGRES_DB: userDb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    volumes:
      - ./postgres-inventory:/data/postgres
    ports:
      - "3333:5432"
    restart: always