spring:
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: http://user-service:8081
          predicates:
            - Path=/api/v1/users/**
          filters:
            - AuthenticationFilter


        - id: auth-service
          uri: http://user-service:8081
          predicates:
            - Path=/api/v1/auth/**


        - id: account-service
          uri: http://account-service:8082
          predicates:
            - Path=/api/v1/accounts/**
          filters:
            - AuthenticationFilter


        - id: transaction-service
          uri: http://transaction-service:8084
          predicates:
            - Path=/api/v1/transactions/**
          filters:
            - AuthenticationFilter

  application:
    name: gateway-service

eureka:
  client:
    service-url:
      defaultZone : http://servicereg:8761/eureka/